# CHAPTER SEVEN – BIM PROJECT EXECUTION PLANNING FOR ORGANIZATIONS 

As stated in the introduction, BIM Plans require typical methods developed by each organization involved.  The purpose of this chapter is to define how organizations can use the BIM Project Execution Planning procedure to develop these typical methods for BIM project implementation.  Figure 7.1 revisits the BIM planning concept to show how organizational means and methods play a vital role in the implementation process.  To obtain the greatest benefit from BIM, the organizations must be willing to develop and share this information with the project team.  

Figure 7-1:  The BIM Project Execution Planning Concept

Organizations should develop internal standards defining how they intend to use BIM as on an organizational level.  By completing the planning process as an organization prior to the BIM Plan for an individual project, each stakeholder will have a starting point for planning and be able to modify existing organizational standards rather than creating entirely new processes.  Additionally, these standards can be shared within the organization to help communicate typical means and methods.  Using a similar four-step procedure with minor modifications, organizations can create BIM Project Execution Planning standards to be used on future projects.
 
## 1.	BIM Mission Statement and Goals

The organization should establish a BIM mission statement.  When creating the mission statement, consider why BIM is important to the organization and the reasons for using BIM such as gaining a competitive advantage on proposals, increasing productivity, improving design quality, reacting to industry demand, satisfying owner requirements, or improving innovation.  Developing a clear mission statement sets the stage for future organizational decisions related to BIM. 

After a mission statement is established, the planning team should develop a list of standard project goals that would be beneficial to the organization and typical projects.  The list can be divided into several categories such as required, recommended, and optional for each project type.  The goals created should be modifiable based on individual project and team characteristics.  Defining standard goals will allow each project team to select from a “menu” of potential goals which will ensure a more comprehensive list of goals along with reduce the time to develop the goals.  

## 2. BIM Uses

An organization should define typical BIM Uses for future projects that align with the goals established within the organization.  Some Uses should be required for every project, while others can only be suggested or optional based on team and project characteristics.  Standard BIM Uses can be determined using the tools for project execution planning such as the BIM Use Analysis Worksheet.  Using this worksheet, the planning teams can assess the current BIM competencies which the organization possesses and the additional competencies required for each use.   When determining which BIM Uses should be required or suggested, it is important to recognize which BIM Uses build upon each other.  If an organization controls multiple processes in a value stream, there will be potential benefits in implementing uses across the multiple processes.  It is also critical that the planning team is not overambitious about which BIM Uses are required and ensure that the selected BIM Uses are realistic for project teams to accomplish.  By determining which BIM Uses will be selected for each project, it will increase the chance of those uses being completed and will also allow the organization to properly evaluate which uses are most beneficial.

## 3. BIM Process Maps

Standard BIM Process Maps should be created to demonstrate the organization’s BIM process(es) to project team members internally and externally.  While the creation of a generic Overview (Level One) Process Map may be beneficial to the project team, this will vary greatly from project to project (depending on which Uses are selected).  Therefore, it is more valuable for organizations to devote time to the Detailed (Level Two) Process Maps.  Multiple process maps may be required for each BIM Use depending upon the software, level of detail, contract type, delivery method, and project type.  Additionally, it may be helpful to create instructions and specifications for each process map generated.  Each project team will then take the level two process maps and customize them based on the project’s and team’s needs.
  
## 4. BIM Information Exchanges

The organizational planning team should establish standard information exchanges for each BIM Use which they perform.  The planning team should identify the information needed for each use; the person who is typically responsible for generating this information; and the preferred format for the information exchange.  It may also be necessary to create multiple information exchanges for each use based on different conditions such as software platform, level of detail, and project complexity.  A typical model element breakdown should also be selected and standardized across the organization when practical.  Understanding the information requirements for each BIM Use will greatly streamline the planning needed for each project and the information exchange step in the Project Execution Planning Procedure will simply focus on finding inconsistency in the data that will be generated by one organization and needed by another.

## 5. BIM Infrastructure 

When planning organizational standards for BIM Project Execution Planning, it is important to consider all the resources and infrastructure required to perform the selected processes.  For each BIM Use selected, the planning team should determine the personnel who will perform each use; establish a plan for adapting each BIM Use’s personnel based on project size, complexity, level of detail and scope; and determine which personnel will typically oversee the BIM Use. 

The organization should design standard collaboration procedures.  Included in this task is crafting standard strategies based on different project types and delivery methods.  The planning team should also determine standard collaboration activities and meetings that will take place on typical projects including frequency and required attendees.  It is also essential that the organization establishes standard electronic communication procedures.  Specific items that should be addressed include file storage and backup systems; standard file folder structures; standard file naming conventions; standard content libraries; and standards for sharing of information both externally and internally. 

Along with collaboration procedures, information management quality assurance and control is valuable for every project.  The quality of a model can significantly impact a project; therefore the organization should have standard quality control processes that are well documented and allow for easy implementation to ensure the level of quality required for each modeling use.  

The planning team should assess the software and hardware needs of each BIM Use and compare the technical infrastructure needs to the current software and hardware.  Necessary upgrades and purchases should be made to ensure that the software and hardware does not limit the successful modeling performance.  If the proper equipment is not in place, it could result in lower productivity and increased time and cost for each BIM Use. 

Typical project deliverables need to be established based on different project characteristics.  Project Owners should establish a list of deliverables for each project based on all the information generated during the planning process.  Designers and contractors should also create a “menu” of BIM services that add value to the overall project. 

It is valuable to consider how BIM will be incorporated into both prime contracts and subcontracts.  Requirements for BIM, including BIM Project Execution Planning, BIM Uses, and information exchanges, should be written into contracts.  The planning team should develop draft language that can be incorporated into contracts, along with developing procedures for team which will allow the organization to identify appropriate team members.

## 6. Developing the BIM Project Execution Plan

By performing organizational level planning, the team can reduce the amount of time spent on each step of the planning process and maintain a manageable planning scope by defining their standard goals, uses, processes, and information exchanges.  The BIM Project Execution Planning Procedure requires organizations to provide information regarding their standard practices, including information exchanges.  While certain contract structures can lead to collaboration challenges, the goal of this procedure is to have the team develop a BIM process containing deliverables that will be beneficial to all members involved.  To reach this goal, the project team needs to have open lines of communication.  To be successful, the team members must buy in to the process and be willing to share this intellectual content with other team members.
